[
  ./autoInputs.nix
  ./builtinFormatters.nix
  ./builtinOverlay.nix
  ./config/apps.nix
  ./config/bundlers.nix
  ./config/checks.nix
  ./config/conflakeModules.nix
  ./config/devShells.nix
  ./config/formatters.nix
  ./config/functor.nix
  ./config/inputs.nix
  ./config/legacyPackages.nix
  ./config/lib.nix
  ./config/nixDir.nix
  ./config/nixosConfigurations.nix
  ./config/nixosModules.nix
  ./config/nixpkgs.nix
  ./config/outputs.nix
  ./config/overlays.nix
  ./config/packages.nix
  ./config/perSystem.nix
  ./config/systems.nix
  ./config/templates.nix
  ./config/templatesDir.nix
  ./config/withOverlays.nix
  ./editorconfig.nix
  ./darwin/darwinConfigurations.nix
  ./darwin/darwinModules.nix
  ./home-manager/homeConfigurations.nix
  ./home-manager/homeModules.nix
  ./moduleArgs.nix
]
