name: Release

on:
  push:
    branches: [release]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@master
      - run: nix flake check --all-systems
  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: go-semantic-release/action@v1
        with:
          allow-initial-development-versions: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
